version: '3'
services:
    mongo:
        image: mongo:3.4.0
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db/
            - ./data/log:/var/log/mongodb/
            - ./data/share:/v-share/
    mongo-express:
            image: mongo-express:latest
            depends_on:
                  - mongo
            ports:
                - "8081:8081"
            env_file:
                - docker-compose/express.env